export const mockUser={
    "login": "Anamika024",
    "id": 83943502,
    "node_id": "MDQ6VXNlcjgzOTQzNTAy",
    "avatar_url": "https://avatars.githubusercontent.com/u/83943502?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Anamika024",
    "html_url": "https://github.com/Anamika024",
    "followers_url": "https://api.github.com/users/Anamika024/followers",
    "following_url": "https://api.github.com/users/Anamika024/following{/other_user}",
    "gists_url": "https://api.github.com/users/Anamika024/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Anamika024/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Anamika024/subscriptions",
    "organizations_url": "https://api.github.com/users/Anamika024/orgs",
    "repos_url": "https://api.github.com/users/Anamika024/repos",
    "events_url": "https://api.github.com/users/Anamika024/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Anamika024/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Anamika Patel",
    "company": null,
    "blog": "",
    "location": "India ",
    "email": null,
    "hireable": null,
    "bio": "BIET Jhansi'24",
    "twitter_username": null,
    "public_repos": 12,
    "public_gists": 0,
    "followers": 2,
    "following": 1,
    "created_at": "2021-05-10T06:51:43Z",
    "updated_at": "2024-04-05T03:14:34Z"
  }